### ISSUE TITLE
Deploy to Kubernetes

### ISSUE THREAD

**Issue by NickHarnau** [veraPDF/verapdf-webapp-server#134]
Hey :) 

First of all thank you for the great work! 
I downloaded the repo and it works perfect in Docker. 
However I would like to bring this into kubernetes and here I am getting problems. 
Do you have a recommended way how to deploy this in kubernetes? 
I tried  several ways like "kompose convert" and manually created an own yml file -> but both ways did not work. 
Do you have experience with deploying this repo to kubernetes? 

Thanks in advance 

Nick

**Comment by bdoubrov** [comment]
Hi Nick,

We mostly use docker-compose in our setup. But one of our partners integrates the service using Kubernetes. Their product (pdfchecker.nl) is open-source. The setup can be found here: https://gitlab.com/pleio/pdfchecker/-/tree/dev/helm/pdfchecker
