### ISSUE TITLE
Quit running job

### ISSUE THREAD

**Issue by NickHarnau** [veraPDF/verapdf-webapp-server#136]
Hey :) 

Is there a possible to quit a Job over the API? Right now it seems only possible to create jobs and get the reports, but not to quit a running job.
I would like to quit a job if for example takes a long time to get a report (like in Issue #135)

**Comment by irinamavrina** [comment]
@NickHarnau Hey!
Yes, you can cancel running job over the API, see [](https://github.com/veraPDF/verapdf-webapp-server/wiki/API-Reference#cancel-job-execution)

**Comment by NickHarnau** [comment]
Ah perfect, thanks! Seems that I  have somehow overseen this point in the wiki ... Next Time I will read more precious ;)

**Comment by NickHarnau** [comment]
Hey :) 
I have just tried to cancel a Job but it is not working. 
I have a PDF (let say PDF_X) that is getting executed and takes some time. Then I want to test another PDF (PDF_Y). 
PDF_X has now the status PROCESSING and PDF_Y has the status WAITING.  (When calling GET api/jobs/{jobID})

Now I want to cancel PDF_X (with: POST api/jobs/{jobID}/cancel). But the status of both PDFs remains on PROCESSING and WAITING. I am also getting a 200 Response when cancelling the job. But it seems like it has no effect... 

Am I doing something wrong? Do I have to take care of something special?

**Comment by irinamavrina** [comment]
Hey)
Right now we support only soft cancel, meaning that if you cancel job during some check running, the job will be cancelled after this particular check is completed. You can see number of completed checks or the name of current running check in progress param.

**Comment by NickHarnau** [comment]
Thanks for your answer!
