### ISSUE TITLE
[BE]: Setup Rabbit-MQ container and create a client to send/receive messages from it

### ISSUE THREAD

**Issue by yuliya-ivaniukovich** [veraPDF/verapdf-webapp-server#9]
In scope of this task container with Rabbit-MQ can be mapped to local port in `.override.yml` file.

In the code we need to create a new module `queue-client`. Client should contain API necessary to communicate with the queue (including _error handling_). 

It should also have a simple cli application to test the availability/health queue: it should send a simple message and then receive it. 
@BezrukovM please comment if additional checks are required in scope of this task. Maybe some unit tests could be written as well?

PS: I prefer cli app for end-to-end test for not not a unit test since we want to use this for troubleshooting purposes in the future and not for a regular check.

**Comment by BezrukovM** [comment]
1. Abstract template listener class which will incapsulate all listen logic with an abstract method `process()`. 
2. Abstract template sender class with send method and abstract method `handleSendToQueueError()`.
All rabbitmq related logic should be incapsulated within the queue-client module.

Add a queue-health-check-cli module with spring cli that implements abstract classes described above and tries to send and receive message.
